version: '3'

services:
    pipelinerunner:
      image: pipelinerunner
      container_name: pipelinerunner
      build:
        context: ./
        dockerfile: ./containers/pipelinerunner/Dockerfile
      volumes:
        - ./:/code
    dashboard:
      image: metabase/metabase
      container_name: dashboard
      ports:
        - "3000:3000"
      volumes:
        - mb_data:/data
      environment:
       - "MB_DB_FILE=data/metabase.db"
volumes:
    mb_data:



